import { expect, test } from '@playwright/test'
import { mkdirSync } from 'node:fs'

const screenshots = '../docs/screenshots/Build2_Task1'
mkdirSync(screenshots, { recursive: true })

test('intermediate viewport widths keep controls inside the page', async ({ page }) => {
  await page.goto('/applications')
  for (const width of [320, 768, 860, 900, 1280]) {
    await page.setViewportSize({ width, height: 900 })
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth), `page overflow at ${width}px`).toBe(true)
  }
})

test('desktop reference layout, shared filtering, details and focus return', async ({ page }) => {
  const failures: string[] = []
  page.on('pageerror', error => failures.push(error.message))
  await page.goto('/applications')
  await expect(page.getByRole('link', { name: 'Product Designer at Cedar & Finch' })).toBeVisible()
  await expect(page.getByRole('region', { name: 'Offer, 0 applications' })).toContainText('No applications here')
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  const longCard = page.getByRole('link', { name: /Senior User Experience Researcher/ })
  expect(await longCard.evaluate(element => element.scrollWidth <= element.clientWidth)).toBe(true)
  await page.screenshot({ path: `${screenshots}/desktop-board.png`, fullPage: true })
  await page.getByRole('searchbox').fill('cedar')
  await page.getByLabel('Sample stage').selectOption('Interview')
  await expect(page.getByText('No matching applications')).toBeVisible()
  await page.getByRole('button', { name: 'List', exact: true }).click()
  await expect(page.getByRole('searchbox')).toHaveValue('cedar')
  await page.getByLabel('Sample stage').selectOption('All stages')
  const card = page.getByRole('link', { name: 'Product Designer at Cedar & Finch' })
  await card.focus()
  await page.keyboard.press('Enter')
  await expect(page.getByRole('dialog')).toBeVisible()
  await expect(page).toHaveURL(/00000000-0000-4000-8000-000000000001/)
  await page.screenshot({ path: `${screenshots}/desktop-detail.png`, animations: 'disabled' })
  // Native modal must prevent focus escaping to the background.
  for (let i = 0; i < 8; i++) await page.keyboard.press('Tab')
  expect(await page.evaluate(() => !!document.querySelector('dialog')?.contains(document.activeElement))).toBe(true)
  await page.keyboard.press('Escape')
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await expect(card).toBeFocused()
  await expect(page.getByRole('searchbox')).toHaveValue('cedar')
  await page.getByRole('searchbox').fill('')
  await page.screenshot({ path: `${screenshots}/desktop-list.png`, fullPage: true })
  expect(failures).toEqual([])
})

test('preview validation, add, reload reset and no data requests', async ({ page }) => {
  const dataRequests: string[] = []
  page.on('request', request => {
    if (['fetch', 'xhr'].includes(request.resourceType())) dataRequests.push(request.url())
  })
  await page.goto('/applications')
  const trigger = page.getByRole('link', { name: 'Add application', exact: true })
  await trigger.click()
  const dialog = page.getByRole('dialog')
  await expect(dialog.getByLabel('Company', { exact: false })).toBeFocused()
  await dialog.getByLabel('Company', { exact: false }).fill('   ')
  await dialog.getByLabel('Role', { exact: false }).fill('Interface Engineer')
  await dialog.getByLabel('Applied date', { exact: false }).fill('2100-01-01')
  await dialog.getByRole('button', { name: 'Add to preview' }).click()
  await expect(dialog.getByRole('alert')).toContainText('Enter a company.')
  await expect(dialog.getByLabel('Role', { exact: false })).toHaveValue('Interface Engineer')
  await page.screenshot({ path: `${screenshots}/form-validation.png`, animations: 'disabled' })
  await dialog.getByLabel('Company', { exact: false }).fill(' Preview Works ')
  await dialog.getByRole('button', { name: 'Add to preview' }).click()
  await expect(page.getByRole('status')).toContainText('Preview Works added to the preview')
  await expect(trigger).toBeFocused()
  await expect(page.getByRole('region', { name: 'Applied, 5 applications' })).toBeVisible()
  await page.getByRole('button', { name: 'List', exact: true }).click()
  await page.getByRole('link', { name: 'Interface Engineer at Preview Works' }).click()
  await expect(page.getByRole('dialog')).toContainText('1 Jan 2100')
  await page.reload()
  await expect(page.getByRole('dialog')).toContainText('Application not found')
  await page.keyboard.press('Escape')
  await expect(page.getByRole('link', { name: 'Interface Engineer at Preview Works' })).toHaveCount(0)
  expect(dataRequests).toEqual([])
})

test('mobile navigation, contained board, stacked list and full-screen details', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto('/applications')
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  const board = page.getByRole('region', { name: /Application board/ })
  expect(await board.evaluate(element => element.scrollWidth > element.clientWidth)).toBe(true)
  await page.screenshot({ path: `${screenshots}/mobile-board.png`, fullPage: true })
  const menu = page.getByRole('button', { name: 'Open navigation' })
  await menu.click()
  await expect(page.getByRole('dialog')).toBeVisible()
  await page.keyboard.press('Escape')
  await expect(menu).toBeFocused()
  await page.getByRole('button', { name: 'List', exact: true }).click()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  await page.screenshot({ path: `${screenshots}/mobile-list.png`, fullPage: true })
  await page.getByRole('link', { name: /Senior User Experience Researcher/ }).click()
  await expect(page.getByRole('dialog')).toHaveCSS('opacity', '1')
  const bounds = await page.getByRole('dialog').boundingBox()
  expect(bounds?.width).toBeCloseTo(390, 1)
  expect(bounds?.height).toBeCloseTo(844, 1)
  await page.screenshot({ path: `${screenshots}/mobile-detail.png`, animations: 'disabled' })
  await page.keyboard.press('Escape')
})

test('reduced motion and board scroll position survive opening a detail', async ({ page }) => {
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await page.setViewportSize({ width: 1100, height: 850 })
  await page.goto('/applications')
  const board = page.getByRole('region', { name: /Application board/ })
  await board.evaluate(element => { element.scrollLeft = element.scrollWidth })
  const before = await board.evaluate(element => element.scrollLeft)
  await page.getByRole('link', { name: 'Frontend Developer at Pebblewave' }).click()
  expect(await page.getByRole('dialog').evaluate(element => getComputedStyle(element).animationName)).toBe('none')
  await page.keyboard.press('Escape')
  expect(await board.evaluate(element => element.scrollLeft)).toBe(before)
  expect(await page.getByRole('button', { name: 'Board', exact: true }).evaluate(element => getComputedStyle(element).transitionDuration)).toBe('0s')
})
